### ISSUE TITLE
Can we automatically publish releases?

### ISSUE THREAD

**Issue by ZacSweers** [ZacSweers/ticktock#29]
- IANA has a "latest" endpoint we can download from and compare to current
- We could set this up on a cron job, checking once a day
- If the version differs from what's in `gradle.properties`
  - Update gradle.properties' version
  - Re-generate tz data in jvm/android artifacts
- Push? Open a PR + auto-merge? Leaning toward build/check + push + tag + upload release

Would also be fine with starting with opening a PR first

Another thing to consider is possibly publishing tzdb.dat and a zip of lazy rules via github releases, allowing them to be downloaded remotely.

Possibly useful: https://github.com/marketplace/actions/git-release

**Comment by msfjarvis** [comment]
If it's any help, joda-time has been auto-updating TZDB using Actions for a while now ([commit](https://github.com/JodaOrg/joda-time/commit/d23b871e78c48c769b21f84f77dfb47408331e73) and [example PR](https://github.com/JodaOrg/joda-time/pull/529)).

**Comment by ZacSweers** [comment]
Opened #31 with an approach adapted from that. Thanks for the tip @msfjarvis
